package org.apache.lucene.queryparser.ext;

/*
 *
 * Copyright(c) 2015, Samsung Electronics Co., Ltd.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.
    
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */ 

import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.search.Query;

/**
 * This class represents an extension base class to the Lucene standard
 * {@link org.apache.lucene.queryparser.classic.QueryParser}. The
 * {@link org.apache.lucene.queryparser.classic.QueryParser} is generated by the JavaCC
 * parser generator. Changing or adding functionality or syntax in the standard
 * query parser requires changes to the JavaCC source file. To enable extending
 * the standard query parser without changing the JavaCC sources and re-generate
 * the parser the {@link ParserExtension} can be customized and plugged into an
 * instance of {@link ExtendableQueryParser}, a direct subclass of
 * {@link org.apache.lucene.queryparser.classic.QueryParser}.
 * 
 * @see Extensions
 * @see ExtendableQueryParser
 */
public abstract class ParserExtension {

  /**
   * Processes the given {@link ExtensionQuery} and returns a corresponding
   * {@link Query} instance. Subclasses must either return a {@link Query}
   * instance or raise a {@link ParseException}. This method must not return
   * <code>null</code>.
   * 
   * @param query
   *          the extension query
   * @return a new query instance
   * @throws ParseException
   *           if the query can not be parsed.
   */
  public abstract Query parse(final ExtensionQuery query) throws ParseException;

}
